import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

import { Card, FormField, SkeletonCard } from '../components';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }

  if (title === 'No Posts Yet') {
    return (
      <div className="col-span-full flex flex-col items-center justify-center py-16 text-center">
        <div className="w-16 h-16 rounded-full bg-[#1a1a2e] border border-[#2a2a3e] flex items-center justify-center mb-4 mx-auto">
          <svg className="w-8 h-8 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
        </div>
        <h3 className="text-white font-semibold text-lg mb-2">No creations yet</h3>
        <p className="text-gray-500 text-sm mb-6">Be the first to generate and share an AI image</p>
        <Link to="/create" className="px-5 py-2.5 rounded-md bg-gradient-to-r from-[#6469ff] to-[#a855f7] text-white text-sm font-medium hover:opacity-90 transition-opacity">
          Create the first one
        </Link>
      </div>
    );
  }

  return (
    <h2 className="mt-5 font-semibold text-gray-500 text-base uppercase tracking-widest col-span-full">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [sortOrder, setSortOrder] = useState('newest');

  const sortOptions = [
    { value: 'newest', label: 'Newest first' },
    { value: 'oldest', label: 'Oldest first' },
    { value: 'az', label: 'Creator A-Z' },
    { value: 'za', label: 'Creator Z-A' },
  ];

  const [searchText, setSearchText] = useState('');
  const [searchTimeout, setSearchTimeout] = useState(null);
  const [searchedResults, setSearchedResults] = useState(null);
  const [searchLoading, setSearchLoading] = useState(false);

  const fetchPosts = async () => {
    setLoading(true);
    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:8080'}/api/v1/post`, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      });
      if (response.ok) {
        const result = await response.json();
        setAllPosts(result.data.reverse());
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchPosts(); }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);
    setSearchLoading(true);
    setSearchTimeout(
      setTimeout(() => {
        const searchResult = allPosts.filter((item) =>
          item.name.toLowerCase().includes(e.target.value.toLowerCase()) ||
          item.prompt.toLowerCase().includes(e.target.value.toLowerCase())
        );
        setSearchedResults(searchResult);
        setSearchLoading(false);
      }, 500),
    );
  };

  const sortedPosts = allPosts ? [...allPosts].sort((a, b) => {
    if (sortOrder === 'oldest') return 0; // allPosts is already newest-first, reverse gives oldest
    if (sortOrder === 'az') return a.name.localeCompare(b.name);
    if (sortOrder === 'za') return b.name.localeCompare(a.name);
    return 0; // newest: keep original order
  }) : null;

  const displayPosts = sortOrder === 'oldest' ? (allPosts ? [...allPosts].reverse() : null) : sortedPosts;

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <div className="flex items-center gap-3 flex-wrap">
          <h1 className="font-extrabold text-white text-[40px] leading-tight tracking-tight">
            The Community <span className="bg-gradient-to-r from-[#6469ff] to-[#a855f7] bg-clip-text text-transparent">Showcase</span>
          </h1>
          {allPosts && (
            <span className="text-sm font-medium text-gray-400 bg-[#1a1a2e] px-3 py-1 rounded-full border border-[#2a2a3e]">
              {allPosts.length} creation{allPosts.length !== 1 ? 's' : ''}
            </span>
          )}
        </div>
        <p className="mt-3 text-gray-300 text-[15px] leading-relaxed">Browse through a collection of imaginative and visually stunning images generated by Picasso AI</p>
      </div>

      <div className="mt-16 flex gap-3 items-end">
        <div className="flex-1">
          <FormField
            labelName="Search posts"
            type="text"
            name="text"
            placeholder="Search something..."
            value={searchText}
            handleChange={handleSearchChange}
          />
        </div>
        {allPosts && (
          <div className="relative">
            <select
              value={sortOrder}
              onChange={(e) => setSortOrder(e.target.value)}
              className="appearance-none pl-4 pr-8 py-3 rounded-lg bg-[#1a1a2e] border border-[#2a2a3e] text-gray-300 text-sm hover:border-[#6469ff] focus:border-[#6469ff] outline-none transition-colors cursor-pointer"
            >
              {sortOptions.map((opt) => (
                <option key={opt.value} value={opt.value}>{opt.label}</option>
              ))}
            </select>
            <svg className="pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </div>
        )}
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="grid lg:grid-cols-3 sm:grid-cols-2 grid-cols-1 gap-3">
            {Array.from({ length: 6 }).map((_, i) => <SkeletonCard key={i} />)}
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-gray-300 text-base mb-3 tracking-wide">
                Showing results for <span className="text-white font-semibold">{searchText}</span>:
              </h2>
            )}
            <div className="grid lg:grid-cols-3 sm:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                searchLoading ? (
                  <>{Array.from({ length: 6 }).map((_, i) => <SkeletonCard key={i} />)}</>
                ) : (
                  <RenderCards data={searchedResults} title="No Search Results Found" />
                )
              ) : (
                <RenderCards data={displayPosts} title="No Posts Yet" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;